version: "3.8"

services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/scripts/docker/postgres-entrypoint.sh:/docker-entrypoint-initdb.d/postgres-entrypoint.sh
      - postgres-data:/var/lib/postgresql/data

  airflow-rbac:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_rbac:airflow_rbac@postgres:5432/airflow_rbac
      - AIRFLOW__CORE__LOAD_EXAMPLES=true
      - AIRFLOW__WEBSERVER__RBAC=true
      - AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE=true
    volumes:
      - ${PWD}/airflow/dags:/opt/airflow/dags
    ports:
      - 8082:8080

volumes:
  postgres-data:
